// Every demo repository, published from the monorepo's demos/ directory
// (see the monorepo's subtrees.tsv). Listed on the home page.
export const DEMO_REPOS_URL = 'https://github.com/testingexamples/';

export const DEMO_REPOS: string[] = [
  'demo-playwright-c-sharp',
  'demo-playwright-c-sharp-for-google-maps',
  'demo-playwright-c-sharp-for-google-search',
  'demo-playwright-c-sharp-for-nhs-wales',
  'demo-playwright-java',
  'demo-playwright-java-for-google-maps',
  'demo-playwright-java-for-google-search',
  'demo-playwright-java-for-nhs-wales',
  'demo-playwright-javascript',
  'demo-playwright-javascript-for-google-maps',
  'demo-playwright-javascript-for-google-search',
  'demo-playwright-javascript-for-nhs-wales',
  'demo-playwright-python',
  'demo-playwright-python-for-google-maps',
  'demo-playwright-python-for-google-search',
  'demo-playwright-python-for-nhs-wales',
  'demo-playwright-rust',
  'demo-playwright-rust-for-google-maps',
  'demo-playwright-rust-for-google-search',
  'demo-playwright-rust-for-nhs-wales',
  'demo-playwright-typescript',
  'demo-playwright-typescript-for-google-maps',
  'demo-playwright-typescript-for-google-search',
  'demo-playwright-typescript-for-nhs-wales',
  'demo-selenium-c-sharp',
  'demo-selenium-c-sharp-for-google-maps',
  'demo-selenium-c-sharp-for-google-search',
  'demo-selenium-c-sharp-for-nhs-wales',
  'demo-selenium-java',
  'demo-selenium-java-for-google-maps',
  'demo-selenium-java-for-google-search',
  'demo-selenium-java-for-nhs-wales',
  'demo-selenium-javascript',
  'demo-selenium-javascript-for-google-maps',
  'demo-selenium-javascript-for-google-search',
  'demo-selenium-javascript-for-nhs-wales',
  'demo-selenium-python',
  'demo-selenium-python-for-google-maps',
  'demo-selenium-python-for-google-search',
  'demo-selenium-python-for-nhs-wales',
  'demo-selenium-rust',
  'demo-selenium-rust-for-google-maps',
  'demo-selenium-rust-for-google-search',
  'demo-selenium-rust-for-nhs-wales',
  'demo-selenium-typescript',
  'demo-selenium-typescript-for-google-maps',
  'demo-selenium-typescript-for-google-search',
  'demo-selenium-typescript-for-nhs-wales',
];
