import { readFileSync } from 'node:fs';
import { test, expect } from '@playwright/test';
import { LOCALES } from '../src/lib/i18n/locales';
import { TOPIC_IDS, slugForTopic } from '../src/lib/i18n/topics';

// Every published page directory /<locale>/<slug>/ has a `.locale-peer-id`
// holding the page's topic id, shared by its translations in all locales.
// The files are generated by `pnpm locale-peer-ids` into static/; this test
// fails if they are missing, stale, or not copied into the build.

for (const locale of LOCALES) {
  test(`${locale}: every page directory has a .locale-peer-id with the topic id`, async () => {
    for (const topicId of TOPIC_IDS) {
      const slug = slugForTopic(locale, topicId);
      const path = slug ? `/${locale}/${slug}/.locale-peer-id` : `/${locale}/.locale-peer-id`;
      // The file in static/ is the source of truth for what gets built.
      const onDisk = readFileSync(`static${path}`, 'utf8');
      expect(onDisk, path).toBe(`${topicId}\n`);
      // And the build copies it (vite preview does not serve dotfiles, but
      // GitHub Pages does, thanks to static/.nojekyll).
      expect(readFileSync(`build${path}`, 'utf8'), path).toBe(`${topicId}\n`);
    }
  });
}

test('peer ids are unique per topic and equal across locales', () => {
  const seen = new Set<string>();
  for (const topicId of TOPIC_IDS) {
    expect(seen.has(topicId)).toBe(false);
    seen.add(topicId);
  }
  expect(seen.size).toBe(TOPIC_IDS.length);
});
