import { readFileSync } from 'node:fs';
import { test, expect } from '@playwright/test';
import { LOCALES } from '../src/lib/i18n/locales';
import { TOPIC_IDS, slugForTopic } from '../src/lib/i18n/topics';

// Every published page directory /<locale>/<slug>/ has a `.locale-peer-id`:
// a 32-character lowercase hexadecimal number then a newline, byte-identical
// across every locale's version of the same topic regardless of its slug
// (spec/locales-for-global-sharing-with-svelte/index.md). The files are
// generated by `pnpm locale-peer-ids` into static/; this test fails if they
// are missing, stale, malformed, or not copied into the build. The ids are
// random (not derived from the topic), so they are kept in the registry.

// The ids are random; the registry that keeps them stable is committed.
const registry: Record<string, string> = JSON.parse(readFileSync('src/lib/i18n/peer-ids.json', 'utf8'));

for (const locale of LOCALES) {
  test(`${locale}: every page directory has a .locale-peer-id with the topic id`, async () => {
    for (const topicId of TOPIC_IDS) {
      const slug = slugForTopic(locale, topicId);
      const path = slug ? `/${locale}/${slug}/.locale-peer-id` : `/${locale}/.locale-peer-id`;
      // The file in static/ is the source of truth for what gets built.
      const onDisk = readFileSync(`static${path}`, 'utf8');
      expect(onDisk, path).toMatch(/^[0-9a-f]{32}\n$/);
      expect(onDisk, path).toBe(`${registry[topicId]}\n`);
      // And the build copies it (vite preview does not serve dotfiles, but
      // GitHub Pages does, thanks to static/.nojekyll).
      expect(readFileSync(`build${path}`, 'utf8'), path).toBe(onDisk);
    }
  });
}

test('a topic has one peer id in every locale, and no two topics share one', () => {
  const byId = new Map<string, string>();
  for (const topicId of TOPIC_IDS) {
    const ids = new Set(
      LOCALES.map((locale) => {
        const slug = slugForTopic(locale, topicId);
        return readFileSync(`static/${locale}/${slug ? slug + '/' : ''}.locale-peer-id`, 'utf8');
      })
    );
    expect(ids.size, topicId).toBe(1);
    const id = [...ids][0];
    expect(byId.has(id), topicId).toBe(false);
    byId.set(id, topicId);
  }
});
